-- delete from image where image.mimetype like '%m%'
--
-- delete from location where location.name like '% %'
--
-- delete from project where project.youtube_url like '%s%'
--
-- delete from artist where artist.name like '% %'
--
-- delete from event where event.name like '% %'
--
-- delete from artist_project where artist_project.id = 'e47c5b41-433f-4172-ae19-f132ae769117'